name: Build and Push to ECR

on:
  push:
    branches:
      - dev # 또는 원하는 브랜치명

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew  # gradlew에 실행 권한 부여

      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to Amazon ECR
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ECR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_ECR_SECRET_KEY }}
          aws-region: ap-northeast-2  # 사용할 리전 설정

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Check and create ECR repository
        run: |
          if ! aws ecr describe-repositories --repository-names ${{ secrets.DEV_ECR_REPOSITORY }} &>/dev/null; then
            echo "Creating ECR repository: ${{ secrets.DEV_ECR_REPOSITORY }}"
            aws ecr create-repository --repository-name ${{ secrets.DEV_ECR_REPOSITORY }}
          else
            echo "ECR repository already exists: ${{ secrets.DEV_ECR_REPOSITORY }}"
          fi

      - name: Build, tag, push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.DEV_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg JAR_FILE=build/libs/*.jar .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Add Dev server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEV_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Dev
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.DEV_EC2_HOST }}
          key: ${{ secrets.DEV_EC2_PRIVATE_KEY }}
          timeout: 30s
          command_timeout: 20m
          script: |
            export ECR_IMAGE=${{ steps.login-ecr.outputs.registry }}/${{ secrets.DEV_ECR_REPOSITORY }}
            export NEW_TAG=${{ github.sha }}
            export SERVER_HOST=${{ secrets.DEV_SERVER_HOST }}
            export MARIA_USERNAME=${{ secrets.DEV_MARIA_USERNAME }}
            export MARIA_PASSWORD=${{ secrets.DEV_MARIA_PASSWORD }}
            export AWS_ECR_ACCESS_KEY=${{ secrets.DEV_AWS_ECR_ACCESS_KEY }}
            export AWS_ECR_SECRET_KEY=${{ secrets.DEV_AWS_ECR_SECRET_KEY }}
            export AWS_SES_ACCESS_KEY=${{ secrets.DEV_AWS_SES_ACCESS_KEY }}
            export AWS_SES_SECRET_KEY=${{ secrets.DEV_AWS_SES_SECRET_KEY }}
            export AWS_CF_DISTRIBUTION=${{ secrets.DEV_AWS_CF_DISTRIBUTION }}
            export AWS_S3_BUCKET=${{ secrets.DEV_AWS_S3_BUCKET }}
            export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            export NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}
            export NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}
            export PORT_ONE_STORE_ID=${{ secrets.PORT_ONE_STORE_ID }}
            export PORT_ONE_API_KEY=${{ secrets.PORT_ONE_API_KEY }}
            export PORT_ONE_WEB_HOOK=${{ secrets.PORT_ONE_WEB_HOOK }}
            export FIREBASE_CONFIG_JSON=${{ secrets.FIREBASE_CONFIG_JSON }}
            export SPRING_PROFILES_ACTIVE=dev
            sudo -E bash /home/ubuntu/deploy.sh
